### ISSUE TITLE
Problems with Spinnaker LDAP authentication

### ISSUE THREAD

**Issue by philchristensen** [foremast/foremast#245]
Thanks for a great tool. I'm having some issues running it against my Spinnaker instance because it requires a login via LDAP.

When I run "foremast validate all", I get the following output:
```
2017-11-14 20:34:25,295 [INFO] foremast.consts:find_config:131 - Loading static configuration file.
2017-11-14 20:34:25,295 [WARNING] foremast.consts:validate_key_values:67 - [base] missing key "git_url", using None.
2017-11-14 20:34:25,295 [WARNING] foremast.consts:validate_key_values:67 - [base] missing key "types", using 'ec2,lambda,s3,datapipeline'.
2017-11-14 20:34:25,296 [WARNING] foremast.consts:validate_key_values:67 - [base] missing key "ami_json_url", using None.
2017-11-14 20:34:25,296 [WARNING] foremast.consts:validate_key_values:67 - [base] missing key "default_securitygroup_rules", using ''.
2017-11-14 20:34:25,296 [WARNING] foremast.consts:validate_key_values:67 - [base] missing key "default_ec2_securitygroups", using ''.
2017-11-14 20:34:25,297 [WARNING] foremast.consts:validate_key_values:67 - [base] missing key "default_elb_securitygroups", using ''.
2017-11-14 20:34:25,297 [INFO] foremast.consts:validate_key_values:58 - Section missing from configurations: [credentials]
2017-11-14 20:34:25,297 [WARNING] foremast.consts:validate_key_values:67 - [credentials] missing key "gitlab_token", using None.
2017-11-14 20:34:25,298 [WARNING] foremast.consts:validate_key_values:67 - [credentials] missing key "slack_token", using None.
2017-11-14 20:34:25,298 [INFO] foremast.consts:validate_key_values:58 - Section missing from configurations: [task_timeouts]
2017-11-14 20:34:25,298 [WARNING] foremast.consts:validate_key_values:67 - [task_timeouts] missing key "default", using 120.
2017-11-14 20:34:25,298 [WARNING] foremast.consts:validate_key_values:67 - [task_timeouts] missing key "envs", using '{}'.
2017-11-14 20:34:25,298 [INFO] foremast.consts:validate_key_values:58 - Section missing from configurations: [whitelists]
2017-11-14 20:34:25,299 [WARNING] foremast.consts:validate_key_values:67 - [whitelists] missing key "asg_whitelist", using ''.
2017-11-14 20:34:25,299 [WARNING] foremast.consts:validate_key_values:67 - [base] missing key "gate_client_cert", using ''.
2017-11-14 20:34:25,299 [WARNING] foremast.consts:validate_key_values:67 - [base] missing key "gate_ca_bundle", using ''.
2017-11-14 20:34:25,299 [INFO] foremast.consts:validate_key_values:58 - Section missing from configurations: [links]
2017-11-14 20:34:25,300 [WARNING] foremast.consts:validate_key_values:67 - [links] missing key "default", using '{}'.
2017-11-14 20:34:25,558 [INFO] foremast.validate:validate_all:24 - Running all validate steps.
InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
Traceback (most recent call last):
  File "/usr/local/bin/foremast", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/foremast/__main__.py", line 116, in main
    args.parsed.func(args)
  File "/usr/local/lib/python3.6/site-packages/foremast/validate.py", line 25, in validate_all
    validate_gate()
  File "/usr/local/lib/python3.6/site-packages/foremast/validate.py", line 13, in validate_gate
    credentials = get_env_credential()
  File "/usr/local/lib/python3.6/site-packages/foremast/utils/credentials.py", line 81, in get_env_credential
    credential = credential_response.json()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
Upon closer inspection, this appears to be because the Gate URL is returning the login form as HTML, instead of the expected JSON:

```
(Pdb) l
352
353  	        """
354  	        try:
355  	            obj, end = self.scan_once(s, idx)
356  	        except StopIteration as err:
357  ->	            raise JSONDecodeError("Expecting value", s, err.value) from None
358  	        return obj, end
[EOF]
(Pdb) p s
'<html><head><title>Login Page</title></head><body onload=\'document.f.username.focus();\'>\n<h3>Login with Username and Password</h3><form name=\'f\' action=\'/login\' method=\'POST\'>\n<table>\n\t<tr><td>User:</td><td><input type=\'text\' name=\'username\' value=\'\'></td></tr>\n\t<tr><td>Password:</td><td><input type=\'password\' name=\'password\'/></td></tr>\n\t<tr><td colspan=\'2\'><input name="submit" type="submit" value="Login"/></td></tr>\n</table>\n</form></body></html>'
```

Any suggestions on how to make this work?

**Comment by jvasallo** [comment]
Hey thanks for the issue! 

We will take a quick peek at this to see if we can get better output, but today foremast only supports x509 auth (or anonymous). We run gate on two ports; the standard port and an additional apiPort. Are you doing the same?

We would be open to adding LDAP auth support if you wish to submit a Pull Request though! We unfortunately don't have an LDAP server to test with today hence why you are probably seeing the error above.

I am not sure if you have the ability to test this, but if you try reaching gate anonymously does the validation call work? I suspect it will, and if you enable x509 it should work too.

**Comment by philchristensen** [comment]
Hmm, that's interesting. Running a second, internal-facing gate with no auth would be fine for my purposes. A quick Google didn't provide much info, is this a common configuration? I've been using Halyard to install Spinnaker and it's not immediately obvious how to do it...

**Comment by ndcampbell** [comment]
@philchristensen I think it is a fairly common configuration, we got the advice from Netflix. We do not run it with no auth, just with x509 auth instead of SAML (or LDAP). Our Gate configuration has:

```
default:
  apiPort: 7777

x509:
  enabled: true
```

which makes gate run on a second api port, bypassing some of the authentication methods. If you then have `x509.enabled: true`, it will make the api port use x509, if that is `false`, I think the api port is authentication-less. 

This is not a separate instance of gate for us (it could be though), just small additions to the gate config that cause the app to run on two ports with different auth methods.  

Unfortunately we do not use Halyard, so I don't know how to configure it from there.

**Comment by philchristensen** [comment]
I think that’s enough info for me to figure it out, thanks very much!

**Comment by philchristensen** [comment]
Incidentally, if anyone stumbles on this thread, details about the feature and directions for doing this with Halyard can be found here: https://www.spinnaker.io/setup/security/authentication/x509/

**Comment by jfcarp** [comment]
As FYI, we were able to get foremast working via LDAP, simply by adding a username, password var in the python http requests (all of them). Low on time at the moment, but will try and submit a pull request next week.

**Comment by jvasallo** [comment]
@jfcarp Good to know you found a solution; Pull Requests are always welcome! We will be on the lookup for it! 👍

**Comment by jfcarp** [comment]
Question for you guys here (as I am not exactly a programmer) but, I was able to get it to work (test app / pipeline) simply by editing the models.py and adding an Authorization Basic [token] to headers. The token being the base64 encoded username/password for LDAP. My question is, how is models.py generated? Without adding this header, I was getting the same error as initially posted in this forum. So, I wasn't sure if creating tests, etc would be necessary, as maybe you guys know of a mechanism to add a header to the project easier or how that file is generated to include an env var perhaps. Also keep in mind this is simply the initial LDAP auth with the gate server, separate from the boto auth for aws items (we simply used its arn from a kubernetes pod). Can provide the output if you would like too. Thanks in advance.

**Comment by jfcarp** [comment]
Alright, sorry all, I got a docker container running for my purposes, but can't seem to figure out how to get the headers into the project without breaking other functionalities, as it is quite fragmented. With a little direction I might spend more time later, but seems the consts.py HEADERS isn't propagated throughout the project and I am not an expert here by any means, but perhaps most files need refactored to add the headers field after url, but I am uncertain and it is too time consuming to do it and not know if it is proper. Anyhow, I am attaching the example header, dockerfile, output, etc for others to pick up hopefully. Cheers.


[foremast.txt](https://github.com/gogoair/foremast/files/1544944/foremast.txt)

**Comment by jvasallo** [comment]
Hey @jfcarp sorry for the delay! Holiday season means a lot of us either out sick or vacationing. Let me review what you mentioned and see if we can work through this together. Do you happen to have a fork with the proposed changes that worked for you?

**Comment by jfcarp** [comment]
No, sorry, no fork. I literally just hacked the models.py, which I believe is the general python http_request model for each of the requests after installing foremast.

1. The line in the models.py, just added the authorization from ENV VAR before Content-Type
→ cat /opt/foremast/venv/lib/python3.5/site-packages/requests/models.py | grep "headers = {"
        headers = {'Authorization': os.getenv('LDAP_AUTH'), 'Content-Type': 'application/json'}

2. Exported the ENV VAR
export LDAP_AUTH="Basic [redacted]"

then it worked... 

Also, 
Foremast was installed in venv under /opt/foremast and there is far more info in the foremast.txt above (script to install foremast the way i did, etc...). Hope it helps and Happy Near Year!

**Comment by jvasallo** [comment]
We are centralizing the way we do Gate Auth. At the moment, we don't have a need for Basic-Auth, but we have a common entry point now at least so you can add it! :)
