### ISSUE TITLE
SQS Lambda Event Trigger getting 'BatchWindow' Key Error

### ISSUE THREAD

**Issue by mjscalexander** [foremast/foremast#401]
Hi Joel, My name is Martin and I work at Gogo. I am trying to trigger my lambda function from SQS polling notification. I see that you removed maxbatchwindow size variable from sqs event lambda trigger about 4 months ago. I am getting the same key error you reported. 

here is the error:
`Traceback (most recent call last):
  File "/tmp/workspace/lambda-prepare/venv/bin/prepare-infrastructure", line 8, in <module>
    sys.exit(prepare_infrastructure())
  File "/tmp/workspace/lambda-prepare/venv/lib/python3.6/site-packages/foremast/runner.py", line 293, in prepare_infrastructure
    runner.create_awslambda()
  File "/tmp/workspace/lambda-prepare/venv/lib/python3.6/site-packages/foremast/runner.py", line 203, in create_awslambda
    lambdaeventobj.create_lambda_events()
  File "/tmp/workspace/lambda-prepare/venv/lib/python3.6/site-packages/foremast/awslambda/awslambdaevent.py", line 67, in create_lambda_events
    event_source=trigger['type'], rules=trigger)
  File "/tmp/workspace/lambda-prepare/venv/lib/python3.6/site-packages/foremast/awslambda/event_source_mapping/event_source_mapping.py", line 86, in create_event_source_mapping_trigger
    MaximumBatchingWindowInSeconds=rules.get('batch_window', event_defaults[event_source]['batch_window']))
KeyError: 'batch_window'`

This is occurring during the initial build phase of my spinnaker lambda pipeline. I am running python3.6 and foremast v4.10.2. This error first occurred for me on 03/11/2020.

**Comment by jvasallo** [comment]
This was patched in v4.15.0: #395 
https://github.com/foremast/foremast/releases/tag/v4.15.0

Can you upgrade to latest and see if it resolves the issue?

**Comment by mjscalexander** [comment]
Thank you Joel, I will speak with Devops about doing so.

**Comment by mjscalexander** [comment]
Thanks the upgrade fixed the issue
